i = int(input('Vvedite chislo')) #'''chislo usera'''
b = int(i**i) #'''berem chislo usera i umnojaev na 6 '''
while i < b : #'''esli chislo usera menshe b  '''
	print (i) # '''on beret i printuet'''
	i*=i  # '''tyt on umnojaet i na 7 '''
